version: "3.7"

services:
  app:
    image: beeracademy/game
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.game-academy-beer.rule=Host(`game.academy.beer`)
        - traefik.http.routers.game-academy-beer.tls.certResolver=le
        - traefik.http.services.game-academy-beer.loadbalancer.server.port=80

networks:
  traefik:
    external: true
