name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build image
      run: docker build -t beeracademy/web .

    - name: Publish image to Docker Hub
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker push beeracademy/web
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy image to production
      run: |
        curl -X POST "$WEBHOOK_URL"
      env:
        WEBHOOK_URLS: ${{ secrets.WEBHOOK_URL }}
